### ISSUE TITLE
Loading asdf

### ISSUE THREAD

**Issue by arunisaac** [luismbo/cl-launch#1]
The documentation (at http://cliki.net/CL-Launch) says that cl-launch looks for asdf in /usr/share/common-lisp/source/cl-asdf, whereas it actually seems to be looking for asdf in /usr/share/common-lisp/cl-asdf.

**Comment by luismbo** [comment]
@arunisaac this is not the official repo. You should contact cl-launch's author. Sorry for the confusion it might have caused.
